# Generated by Django 4.0.4 on 2022-04-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование заметки')),
                ('text', models.TextField(verbose_name='Текст заметки')),
                ('date_published', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
            ],
        ),
    ]
