# Generated by Django 4.0.4 on 2022-04-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='slug',
            field=models.SlugField(default=1, max_length=148, unique=True, verbose_name='Уникальная ссылка'),
            preserve_default=False,
        ),
    ]
